Mall/Areas/SysManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mall.Areas.SysManagement.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /SysManagement/Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Mall/Controllers/FrameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mall.Models;
using Mall.ViewModels;
using System.Drawing;
using System.IO;
using System.Drawing.Imaging;
using JETLib.Common;
namespace Mall.Controllers
{
    public class FrameController : Controller
    {

        MallDB db = new MallDB();
        //
        // GET: /Frame/

        public ActionResult Index()
        {

            return View();
        }

        public ActionResult FrameIt(int goodId, int paintsizeId)
        {
            PaintFrameViewModel Model = new PaintFrameViewModel
            {
                FrameList = db.Frames.ToList(),
                ChosenSize = db.PaintSizes.Single(p => p.ID == paintsizeId),
                Paint = db.Goods.Single(g => g.ID == goodId),
                PaintFramePrice = 0
            };
            return View(Model);
        }

        public ActionResult FramePaint(int gid, int fid)
        {
            string paintPath = db.Goods.Single(g => g.ID == gid).Img;
            string framePath = db.Frames.Single(f => f.ID == fid).Img;
            //Image img = FrameIt(Server.MapPath("~/"+paintPath), Server.MapPath(@"~/"+framePath), Color.White);
            Image img = FrameIt(Server.MapPath("~/" + paintPath), db.Frames.Single(f => f.ID == fid), Color.White);
            img = GetFramePaint(db.Goods.Single(g => g.ID == gid), db.Frames.Single(f => f.ID == fid), Color.Pink);
            MemoryStream stream = new MemoryStream();
            img.Save(stream, ImageFormat.Png);
            return File(stream.ToArray(), @"image/png");
        }



        /// <summary>
        /// 为画加框
        /// </summary>
        /// <param name="curPaint">需要加框的画的地址</param>
        /// <param name="curFrame">画框地址</param>
        private Image FrameIt(string curPaint, string curFrame, Color bgColor)
        {
            //设置画和边框
            Bitmap frame = new Bitmap(curFrame);
            Bitmap paint = new Bitmap(curPaint);

            paint = new Bitmap(ImgHelper.ScalingInMode(paint, frame.Width - 200, frame.Height - 200));
            Bitmap anthorFrame = new Bitmap(curFrame);
            //绘制画框
            Graphics g = Graphics.FromImage(frame);
            g.Clear(bgColor);

            g.FillRectangle(new TextureBrush(new Bitmap(curFrame)), 0, 0, frame.Width, frame.Height);

            anthorFrame.RotateFlip(RotateFlipType.Rotate180FlipNone);
            TextureBrush tb = new TextureBrush(anthorFrame);
            Point[] ps = new Point[]{
                new Point{ X=1000,Y=0},
                new Point{ X=0,Y=1000},
                new Point{ X=1000,Y=1000}
            };
            g.FillPolygon(tb, ps);
            int startX = (frame.Width - paint.Width) / 2;
            int startY = (frame.Height - paint.Height) / 2;
            TextureBrush tb2 = new TextureBrush(paint);

            //g.FillRectangle(tb2,startX,startY,paint.Width,paint.Height);
            Rectangle rect = new Rectangle(startX, startY, paint.Width, paint.Height);
            g.DrawImage(paint, rect);

            //ThePic.Image = frame;
            //g.Dispose();
            return frame;

        }
        /// <summary>
        /// 为画加框
        /// </summary>
        /// <param name="curPaint">需要加框的画的地址</param>
        /// <param name="curFrame">画框地址</param>
        private Image FrameIt(string curPaint, Frames theFrame, Color bgColor)
        {
            //设置画和边框
            Bitmap oFrame = new Bitmap(Server.MapPath("~/" + theFrame.Img));

            Bitmap frame = new Bitmap(Server.MapPath("~/" + theFrame.Img));
            Bitmap paint = new Bitmap(curPaint);

            paint = new Bitmap(ImgHelper.ScalingInMode(paint, frame.Width - 100, frame.Height - 100));
            int frameWidth = paint.Width + 100 + theFrame.Width;
            int frameHeight = paint.Height + 100 + theFrame.Width;

            //绘制画框
            Graphics g = Graphics.FromImage(frame);


            //frame = new Bitmap(frame, frameWidth, frameHeight);
            g.DrawImage(frame, new Point(frameWidth, frameHeight));
            Bitmap anthorFrame = new Bitmap(frame);
            g.Clear(bgColor);

            g.FillRectangle(new TextureBrush(oFrame), 0, 0, frameWidth, frameHeight);

            anthorFrame.RotateFlip(RotateFlipType.Rotate180FlipNone);
            TextureBrush tb = new TextureBrush(anthorFrame);
            Point[] ps = new Point[]{
                new Point{ X=frame.Width,Y=0},
                new Point{ X=0,Y=frame.Height},
                new Point{ X=frame.Width,Y=frame.Height}
            };
            g.FillPolygon(tb, ps);
            int startX = (frame.Width - paint.Width) / 2;
            int startY = (frame.Height - paint.Height) / 2;
            TextureBrush tb2 = new TextureBrush(paint);

            //g.FillRectangle(tb2,startX,startY,paint.Width,paint.Height);
            Rectangle rect = new Rectangle(startX, startY, paint.Width, paint.Height);
            g.DrawImage(paint, rect);

            //ThePic.Image = frame;
            //g.Dispose();
            return frame;

        }

        public Image GetFramePaint(Goods paint, Frames frame, Color bgColor)
        {

            //先比较图片和框的尺寸，如果图片的尺寸较大，就缩图片适应框，如果框的尺寸较大，就缩框适应图片
            Bitmap frameImage = new Bitmap(Server.MapPath("~/"+ frame.Img) );
            Bitmap paintImage = new Bitmap(Server.MapPath("~/"+ paint.Img) );
            int frameWidth = frame.Width;
            //如果画比框大,则缩小画到适合框的比例，与框之间留白100px
            if (paintImage.Width > frameImage.Width - frameWidth || paintImage.Height > frameImage.Height - frameWidth)
            {
                //先根据框的大小，缩放画的尺寸到适合框的大小
                paintImage = new Bitmap(ImgHelper.ScalingInMode(paintImage, frameImage.Width - 100 - frameWidth, frameImage.Height - 100 - frameWidth));
            }
            //定义装框后画的尺寸
            int paintFramedWidth = paintImage.Width + frameWidth + 100;
            int paintFramedHeight = paintImage.Height + frameWidth + 100;
            Bitmap thumbFrame = new Bitmap(paintFramedWidth, paintFramedHeight);
            using (Graphics g = Graphics.FromImage(thumbFrame))
            {
                g.Clear(bgColor);
                //g.FillRectangle(new TextureBrush(frameImage), new Rectangle(0, 0, paintFramedWidth, paintFramedHeight));
                //此时，frameImage已经变成了缩放后需要的大小
                g.DrawImage(frameImage, new Rectangle(0, 0, paintFramedWidth, paintFramedHeight));
                //左上，右上，左下
                Point[] ps = new Point[] { 
                    new Point(0,0),
                    new Point(paintFramedWidth,0),
                    new Point(0,paintFramedHeight)
                };
                g.DrawImage(frameImage,ps,new Rectangle(0,0,paintFramedWidth,paintFramedHeight),GraphicsUnit.Pixel);
                Bitmap rightFrame = new Bitmap(thumbFrame);
                rightFrame.RotateFlip(RotateFlipType.Rotate180FlipNone);
                TextureBrush tb = new TextureBrush(rightFrame);
                Point[] rightPs = new Point[]{
                    new Point{ X=rightFrame.Width,Y=0},
                    new Point{ X=rightFrame.Width-frameWidth,Y=frameWidth},
                    new Point{ X=frameWidth,Y=rightFrame.Height-frameWidth},
                    new Point{ X=0,Y=rightFrame.Height},
                    new Point{ X=rightFrame.Width,Y=rightFrame.Height}
                };
                //画另半边框
                g.FillPolygon(tb, rightPs);
                //画画心
                g.DrawImage(paintImage, new Point((thumbFrame.Width - paintImage.Width) / 2, (thumbFrame.Height - paintImage.Height) / 2));

                
            }
            return thumbFrame;
        }

    }
}

Mall/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mall.Models;
using Mall.ViewModels;
namespace Mall.Controllers
{
    public class HomeController : Controller
    {
        Mall.Models.MallDB db = new Models.MallDB();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SalerRoom()
        {
            IList<SalerRoomGoods> modelList = new List<SalerRoomGoods>();
            db.Goods.OrderByDescending(m => m.ID).ToList().ForEach(g =>
            {
                modelList.Add(new SalerRoomGoods(g));
            });
            return View(modelList);
        }

        public ActionResult Details(int id)
        {
            SalerRoomGoods model = new SalerRoomGoods(id);
            //model.Paint = db.Goods.First(g => g.ID == id);
            //model.PrintSize = db.PaintSizes.Where(p => p.GoodsID == id).ToList();
            return View(model);
        }

        public ActionResult GetPaintSize(int id)
        {
            PaintSizes model=db.PaintSizes.First(p=>p.ID==id);
            return Json(new
            {
                Width=model.Width,
                Height=model.Height,
                Price=model.Price

            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ShoppingCart()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

Mall/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Mall.Models;
using Mall.ViewModels;
namespace Mall.Controllers
{
    public class ShoppingCartController : Controller
    {
        Mall.Models.MallDB db = new Models.MallDB();

        //
        // GET: /ShoppingCart/

        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            return View(viewModel);
        }

        public ActionResult AddToCart(FormCollection fc)
        {
            //这里，需要赋的值有，商品编号，是否装框，框id，尺寸id
            var cart = ShoppingCart.GetCart(this.HttpContext);
           // Mall.Models.ViewModels.ShoppingCartPaintItem paintItem = new Mall.Models.ViewModels.ShoppingCartPaintItem(Convert.ToInt32(fc["GoodsId"]),
              //  Convert.ToInt32(fc["PaintSizeId"]),Convert.ToBoolean(fc["IsFrame"]),Convert.ToBoolean(fc["IsFrame"])?Convert.ToInt32(fc["FrameId"]):1);

            Cart cartItem = new Cart {
                GoodsId = Convert.ToInt32(fc["GoodsId"]),
                IsFrame = Convert.ToBoolean(fc["IsFrame"]),
                PaintSizeId = Convert.ToInt32(fc["PaintSizeId"]),
                FrameId = Convert.ToBoolean(fc["IsFrame"]) ? Convert.ToInt32(fc["FrameId"]) : 1
            };

            cart.AddToCart(cartItem);
            return RedirectToAction("Index");
        }

    }
}

Mall/Views/Home/About.cshtml
@{
    ViewBag.Title = "关于我们";
}

<h2>关于</h2>
<p>
     将内容放置在此处。
</p>

Mall/Views/Home/Details.cshtml
@model Mall.ViewModels.SalerRoomGoods

@{
    ViewBag.Title = "Details";
}

@section HeadStyle{
    <link href="@Url.Content("~/css/saleroom.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/css/buy.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/css/jquery.jqzoom.css")" rel="stylesheet" type="text/css" />
}
@section HeadScript{
    <script src="@Url.Content("~/Scripts/jquery.LoadImage.js")" type="text/javascript"></script>
<script type="text/javascript" src="@Url.Content("~/scripts/jquery.jqzoom-core.js")"></script>
}

@section PagePath{
<!--path:start-->
<div class="page-path">
    <a href="#" class="homeLink"></a><span>--</span><a href="#" class="linkOne">馆藏高仿</a><span>--</span><a href="#" class="linkTwo">山水</a><span>--</span><a href="#" class="linkTwo">《金藻图》明·缪辅</a>
</div>
<!--path:end-->
}
<div id="container">
<div class="buy">
    	<!--proAttr:start-->
        
    	<div class="pro-img fl">
        	<table>
            <tr>
            	<td width="440" height="500" align="center" valign="middle">
                <a href="@Url.Content("~")@Model.Paint.Img" class="t-img" title="@Model.Paint.Name"><img src="@Url.Content("~")@Model.Paint.Thumb" /></a>
                </td>
            </tr>
            </table>
        </div>
        <div class="pro-attr fl">
        	<table class="mb50" width="100%" border="0">
              <tr>
                <td height="35" class="f14 fb txt574841">@Model.Paint.Name</td>
                <td></td>
              </tr>
              <tr>
                <td>@Model.Paint.Summary</td>
                <td>编号#：@Model.Paint.NO</td>
              </tr>
            </table>
			
<table class="mb50" width="100%" border="0">
              <tr>
                <td width="200" height="35" class="f14 fb txt574841">尺寸</td>
                <td class="f14 fb txt574841">价格</td>
              </tr>
              <tr>
                <td id="curSize">@Model.ChosenSize.Width.ToString()×@Model.ChosenSize.Height.ToString()cm</td>
                <td><span id="curPrice" class="txt-red fb txtRed">￥@Model.ChosenSize.Price.ToString()</span></td>
              </tr>
            </table>
            
            <table class="mb50" width="400" border="0">
                  <tr>
                    <td height="30" class="txt574841 fb f14">7种尺寸可选</td>
                    <td width="100" class="txt574841 fb f14">制作周期</td>
                    <td width="50" class="txt574841 fb f14">费用</td>
                  </tr>
                  
                  @foreach (var item in Model.PrintSize)
                  {
                  <tr pid="@item.ID" class="printSize">
                    <td height="20">@item.Width×@item.Height cm</td>
                    <td>@item.Cycle</td>
                    <td>￥@item.Price</td>
                  </tr>   
                  }

                </table>
				<form method="post" id="cartForm" action="@Url.Action("AddToCart","ShoppingCart")">
                <input type="hidden" id="GoodsID" name="GoodsID" value="@Model.Paint.ID" />
                <input type="hidden" id="isFrame" name="IsFrame" value="false" />
                <input type="hidden" id="FrameId" name="FrameId" value="1" />
                <input type="hidden" id="PaintSizeId" name="PaintSizeId" value="@Model.ChosenSize.ID" />
                <input type="hidden" id="Others" name="Others" value="0" />
                <table class="mb50 buy-bar" width="100%" border="0">
					<tr>
                    	<td><a class="cart" id="addToCart" href="#">购物车</a></td>
                    	<td><a id="FrameIt" href="">Frame It</a></td>
                    	<td><a href="#">加入收藏</a></td>
                    	<td><a href="#">浏览大图</a></td>
                    	<td><a href="#">放入实景</a></td>
                    </tr>
                </table>
               </form>
        </div>
        <div class="cl"></div>
        <!--proAttr:end-->
        <!--frame:start-->
        <div class="frame mt20">
       	  <h3 class="tit-01"><span>装框真实效果</span></h3>
            <table width="100%" class="mt15" border="0">
              <tr>
                <td height="305" style="border-right:1px dotted #7d7d7d; border-bottom:1px dotted #7d7d7d;"><table width="440" border="0">
                  <tr>
                    <td align="center"><a href="#"><img src="@Url.Content("~/res/08.jpg")" width="128" height="202" /></a></td>
                    <td align="center"><img src="@Url.Content("~/res/f01.jpg")" width="91" height="91" /></td>
                    <td align="center"><img src="@Url.Content("~/res/f02.jpg")" alt="" width="91" height="91" /></td>
                  </tr>
                  <tr>
                    <td height="60" colspan="3" align="center"><img src="@Url.Content("~/images/other/num-01.gif")" width="47" height="47" /></td>
                  </tr>
                </table></td>
                <td style=" border-bottom:1px dotted #7d7d7d;"><table width="440" border="0">
                  <tr>
                    <td align="center"><a href="#"><img src="@Url.Content("~/res/09.jpg")" alt="" width="109" height="202" /></a></td>
                    <td align="center"><img src="@Url.Content("~/res/f03.jpg")" alt="" width="91" height="91" /></td>
                    <td align="center"><img src="@Url.Content("~/res/f04.jpg")" alt="" width="91" height="91" /></td>
                  </tr>
                  <tr>
                    <td height="60" colspan="3" align="center"><img src="@Url.Content("~/images/other/num-02.gif")" alt="" width="47" height="47" /></td>
                  </tr>
                </table></td>
              </tr>
              <tr>
                <td height="305" bgcolor="eeeeee" style="border-right:1px dotted #7d7d7d;"><table width="440" border="0">
                  <tr>
                    <td align="center"><a href="#"><img src="@Url.Content("~/res/10.jpg")" alt="" width="153" height="202" /></a></td>
                    <td align="center"><img src="@Url.Content("~/res/f05.jpg")" alt="" width="91" height="90" /></td>
                    <td align="center"><img src="@Url.Content("~/res/f06.jpg")" alt="" width="91" height="90" /></td>
                  </tr>
                  <tr>
                    <td height="60" colspan="3" align="center"><img src="@Url.Content("~/images/other/num-03.gif")" alt="" width="47" height="47" /></td>
                  </tr>
                </table></td>
                <td bgcolor="eeeeee"><table width="440" border="0">
                  <tr>
                    <td align="center"><a href="#"><img src="@Url.Content("~/res/11.jpg")" alt="" width="153" height="202" /></a></td>
                    <td align="center"><img src="@Url.Content("~/res/f07.jpg")" alt="" width="91" height="90" /></td>
                    <td align="center"><img src="@Url.Content("~/res/f08.jpg")" alt="" width="91" height="90" /></td>
                  </tr>
                  <tr>
                    <td height="60" colspan="3" align="center"><img src="@Url.Content("~/images/other/num-04.gif")" alt="" width="47" height="47" /></td>
                  </tr>
                </table></td>
              </tr>
            </table>
			<div class="cl"></div>
        </div>
        
        <div class="mt20">
       	<h3 class="tit-01"><span>您可能会喜欢呦</span></h3>
          <ul class="ul-01">
           	  <li>
                  <a href="#"><img src="@Url.Content("~/res/12.jpg")" /></a>
                  <p><a href="#">墨竹图 宋·文同</a></p>
              </li>
           	  <li>
                  <a href="#"><img src="@Url.Content("~/res/13.jpg")" /></a>
                  <p><a href="#">墨竹图 宋·文同</a></p>
              </li>
           	  <li>
                  <a href="#"><img src="@Url.Content("~/res/14.jpg")"  /></a>
                  <p><a href="#">墨竹图 宋·文同</a></p>
              </li>
           	  <li>
                  <a href="#"><img src="@Url.Content("~/res/15.jpg")" /></a>
                  <p><a href="#">墨竹图 宋·文同</a></p>
              </li>
          </ul>
          <div class="cl"></div>
        </div>
		<div><a href="#" style="float:right;" class="top"></a></div>
        <!--frame:end-->
        <div class="cl"></div>
    </div>

<script type="text/javascript">

    $(function () {
        $(".printSize").click(function () {
            var pid = $(this).attr("pid");
            $.getJSON("@Url.Action("GetPaintSize")/"+pid,function(json){
//                alert(json.Width+json.Height);
                var size=json.Width+" × " + json.Height +" cm";
                $("#curSize").html(size);
                $("#curPrice").html("￥"+json.Price);
                $("#")
            });
            $(".printSize").removeClass("bdRed");
            $(this).addClass("bdRed");
        });
        $("#addToCart").click(function(){
            $("#cartForm").submit();
            return false;
        });

        $("#FrameIt").click(function(){
            window.location.href="@Url.Action("FrameIt","Frame")?goodId="+$("#GoodsID").val()+"&paintsizeId="+$("#PaintSizeId").val();
            return false;
        });
    })
</script>
@section FooterScript{

$(function() {
            //图片垂直居中
           /* $(".pro-img .t-img img").each(function() {
                src = $(this).attr("src");
                $(this).LoadImage(true, 314, 479, "@Url.Content("~/images/other/loading.gif")");
            })*/
            $(".ul-01 img").each(function() {
                src = $(this).attr("src");
                $(this).LoadImage(true, 98, 150, "@Url.Content("~/images/other/loading.gif")");
            })
			
			//jqzoom
			$(document).ready(function(){  
				var options = {  
						zoomType: 'standard',  
						lens:true,  
						preloadImages: true,  
						alwaysOn:false,  
						zoomWidth: 450,  
						zoomHeight: 450  
						//...MORE OPTIONS  
				};  
				$('.t-img').jqzoom(options);  
			}); 
            //隔行变色
            $(".printSize:even").addClass("bgEEE");
            
        })

}

Mall/Views/Home/Index.cshtml
@{
    ViewBag.Title = "主页";
}

@section HeadStyle{
    <link href="@Url.Content("~/css/index.css")" rel="stylesheet" type="text/css" />
}

<div id="container">
<div class="line-1 dot-bot-line">
    	<dl class="line1-dl">
            <dt><a class="line1-dl-tit" href="#">家庭装饰</a><a class="line1-dl-frame" href="#">Frame it</a></dt>
            <dd><img src="res/01.jpg" width="450" height="314" /></dd>
        </dl>
        <dl class="line1-dl">
            <dt><a class="line1-dl-tit" href="#">酒店、写字楼</a><a class="line1-dl-frame" href="#">Frame it</a></dt>
            <dd><img src="res/02.jpg" width="450" height="314" /></dd>
        </dl>
        <div class="cl"></div>
    </div>
    <div class="cl"></div>
	<div class="line-box mt10">
    	<div class="line-box-tit"><span></span><a href="#">自由换画框</a></div>
        <div class="line-box-con h330 tc">
     		<img src="images/index/frame-step.jpg" width="912" height="316" alt="自由换画框" />
        </div>
        <div class="cl"></div>
    </div>
    <div class="cl"></div>
<div class="line-box mt10">
    	<div class="line-box-tit"><span></span><a href="#">壁彩九天</a></div>
        <div class="line-box-con tc">
          <div class="eg-item">
            <a class="img" href="#">
                <img src="images/index/paint01.jpg" width="300" height="220" /> 
            </a>
            <div class="fl w460">
                <dl>
                    <dt><img src="images/index/icon01.jpg" width="21" height="21" /></dt>
                    <dd>
                   <p> <span style=" color:red;">北京壁</span><span style="color:#fecc35;">彩</span><span style="color:green;">九天</span>文化发展公司，2005年建立，目前国内颇具声誉的、以国际博物馆复制技术为基础就馆藏传统书画、陶瓷进行高仿，近年来进军家居配饰市场。</p>
                    </dd>
                    <div class="cl"></div>
                </dl>
                <dl>
                    <dt>&nbsp;</dt>
                    <dd>
                    <p><span style=" color:red;">北京壁</span><span style="color:#fecc35;">彩</span><span style="color:green;">九天</span>文化发展公司，2005年建立，目前国内颇具声誉的、以国际博物馆复制技术为基础就馆藏传统书画、陶瓷进行高仿，近年来进军家居配饰市场。</p>
                    </dd>
                    <div class="cl"></div>
                </dl>
            </div>
          </div>
          <div class="cl"></div>
          <div class="eg-item">
            <a class="img" href="#">
                <img src="images/index/paint02.jpg" width="300" height="220" /> 
            </a>
            <div class="fl w460">
                <dl>
                    <dt><img src="images/index/icon02.jpg" width="21" height="21" /></dt>
                    <dd>
                   <p> <span style=" color:red;">北京壁</span><span style="color:#fecc35;">彩</span><span style="color:green;">九天</span>文化发展公司，2005年建立，目前国内颇具声誉的、以国际博物馆复制技术为基础就馆藏传统书画、陶瓷进行高仿，近年来进军家居配饰市场。</p>
                    </dd>
                    <div class="cl"></div>
                </dl>
                <dl>
                    <dt>&nbsp;</dt>
                    <dd>
                    <p><span style=" color:red;">北京壁</span><span style="color:#fecc35;">彩</span><span style="color:green;">九天</span>文化发展公司，2005年建立，目前国内颇具声誉的、以国际博物馆复制技术为基础就馆藏传统书画、陶瓷进行高仿，近年来进军家居配饰市场。</p>
                    </dd>
                    <div class="cl"></div>
                </dl>
            </div>
          </div>
          <div class="cl"></div>
          <div class="eg-item">
            <a class="img" href="#">
                <img src="images/index/paint03.jpg" width="300" height="220" /> 
            </a>
            <div class="fl w460">
                <dl>
                    <dt><img src="images/index/icon03.jpg" width="21" height="21" /></dt>
                    <dd>
                   <p> <span style=" color:red;">北京壁</span><span style="color:#fecc35;">彩</span><span style="color:green;">九天</span>文化发展公司，2005年建立，目前国内颇具声誉的、以国际博物馆复制技术为基础就馆藏传统书画、陶瓷进行高仿，近年来进军家居配饰市场。</p>
                    </dd>
                    <div class="cl"></div>
                </dl>
                <dl>
                    <dt>&nbsp;</dt>
                    <dd>
                    <p><span style=" color:red;">北京壁</span><span style="color:#fecc35;">彩</span><span style="color:green;">九天</span>文化发展公司，2005年建立，目前国内颇具声誉的、以国际博物馆复制技术为基础就馆藏传统书画、陶瓷进行高仿，近年来进军家居配饰市场。</p>
                    </dd>
                    <div class="cl"></div>
                </dl>
            </div>
          </div>
          <div class="cl"></div>
        </div>
</div>